FromDoppler/doppler-editors-webapp

- .prettierrc
- demo/demo.html
- public/index.html
- src/index.css
Hi team!
It seems that Prettier tries to make honor to EditorConfig configurations (see [here](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options)), but they do it in a relaxed way. For example, if EditorConfig's `max_line_length` configuration is `100`, sometimes Prettier generates lines of 104 characters.
So, I kept EditorConfig's `max_line_length` configuration at `100` and added a new `printWidth` configuration for Prettier at `80`.
It should work fine.
> Prettier & EditorConfig inconsistency

- src/index.tsx
I was defining the property basename all the time. So, the default value was never read.
> fix: fix how the old basename configuration is being read

- src/abstractions/app-session/app-session-state-accessor.ts
- src/abstractions/app-session/app-session-state-monitor.ts
- src/abstractions/app-session/app-session-state.ts
- src/abstractions/app-session/index.ts
- src/abstractions/common/result-types.ts
- src/abstractions/configuration.ts
- src/abstractions/doppler-legacy-client/index.ts
- src/abstractions/services.ts
- src/components/App.tsx
- src/components/AppSessionStateContext.tsx
- src/components/NavigateToExternalUrl.tsx
- src/components/RequireAuth.test.tsx
- src/components/RequireAuth.tsx
- src/components/SessionDemo.tsx
- src/composition-root.ts
- src/default-configuration.ts
- src/implementations/SingletonLazyAppServicesContainer.ts
- src/implementations/app-session/pulling-app-session-state-monitor.ts
- src/implementations/dummies/doppler-legacy-client.tsx
- src/index.tsx
- src/utils/index.ts
Hi @Cromeror, @maurocardinali, @jcamposmk, @ck-makingsense, @leoslopez and team!
We are following the same approach as the _"Original" WebApp_: we are pulling to `GetUserData` and, based on its response, we update our internal representation of the session.
When a component depends on an authenticated session and the session status is _non-authenticated_, it redirects to the log-in page:
When the status is _unknown_, it waits, and when the status is _authenticated_, it simply works:
We have also applied an improvement over _"Original" WebApp_ behavior, when the session data is not important, only the status, we have a hook only for the status, so, when the session data is updated, but the status is the same, it avoids unnecessary renderings:
See `SessionDemo` component for more details. …
> DE-415 - User Session

- src/abstractions/app-session/app-session-state.ts
- src/abstractions/doppler-legacy-client/index.ts
- src/components/Editor.tsx
- src/implementations/dummies/doppler-legacy-client.tsx
We will not use the email field in Unlayer's user model.
> chore: remove wrong email field from unlayerUser

- demo/index.html
Related to https://github.com/MakingSense/doppler-swarm/pull/589 but in our local demo index.html file.
Some examples:
> chore: allow to parse version and nocache from querystring in demo page

- Dockerfile
- src/components/AppSessionStateContext.tsx
Hi team, 
We had an issue with `useEffect` dependencies, but it was not been validated by our CI. These changes fix the issue and the CI behavior.
> Fix useEffect dependency

- demo/index.html
- src/abstractions/configuration.ts
- src/composition-root.ts
- src/default-configuration.ts
Hi team! 
I think that it will be really useful because it will allow us to work without the backend during development and also to test things in other environments.
Related to https://github.com/MakingSense/doppler-swarm/pull/590
If you add the query string ew_dummy=true it will use dummy versions of the backend adapters.
In your local environment, you could edit the default configuration, or even we can make it dummy by default 🤔
> DE-430 - Allow dummy behavior

- src/abstractions/doppler-legacy-client/index.ts
- src/implementations/DopplerLegacyClientImpl.test.ts
- src/implementations/DopplerLegacyClientImpl.ts
- src/implementations/dummies/doppler-legacy-client.tsx
There was a bug parsing the doppler legacy user data and it was redirecting to the login over and over.
These changes fix the issue.
> fix: fix the structure of doppler legacy user data

- src/components/Campaign.tsx
I was trying to render the error object as it was, but the error is something like: 
```
Uncaught Error: Objects are not valid as a React child (found: Error: X). If you meant to render a collection of children, use an array instead.
```
Now, I am serializing it before rendering.
Obviously, it is something temporal, in the future, these kinds of errors should be rendered in a nicer way.
I did not change the tests, because the test `should show loading and then error when getCampaignContent is not successful` is already covering this scenario, but it seems that in the reality, the behavior is different from the test.
> fix: render campaign unexpected error as string

- src/abstractions/common/result-types.ts
- src/abstractions/doppler-legacy-client/index.ts
- src/abstractions/html-editor-api-client/index.ts
- src/components/Campaign.tsx
- src/implementations/DopplerLegacyClientImpl.ts
- src/implementations/HtmlEditorApiClientImpl.ts
- src/implementations/dummies/doppler-legacy-client.tsx
- src/implementations/dummies/html-editor-api-client.tsx
Hi @FromDoppler/doppler-editors and @FromDoppler/doppler-webapp!
During my vacations, I have learned a little more about generic types in TypeScript and I found the fix for a `// TODO` that we had in [Doppler WebApp](https://github.com/FromDoppler/doppler-webapp) for more than 3 years: https://github.com/FromDoppler/doppler-webapp/blob/ff9d697526b7f8338a8f70a8b2846a1dc1f5f22d/src/doppler-types.ts#L11
@jcamposmk maybe you can apply this same change in [Doppler WebApp](https://github.com/FromDoppler/doppler-webapp), I know that it is not so important, but is nicer.
This is only a change in the types, the behavior is exactly the same as before. As a second step, I am thinking about removing `UnexpectedError`s and using exceptions for them.
In my opinion, it is very easy to forget a catch-all …
> refactor: improve result representation types

- src/implementations/HtmlEditorApiClientImpl.test.ts
- src/implementations/HtmlEditorApiClientImpl.ts
Hi team!
This is the complementary change to https://github.com/FromDoppler/doppler-html-editor-api/pull/21
> fix: update HTML Editor API client to the new schema

- src/abstractions/common/result-types.ts
- src/abstractions/doppler-legacy-client/index.ts
- src/components/Campaign.test.tsx
- src/components/Campaign.tsx
- src/implementations/DopplerLegacyClientImpl.test.ts
- src/implementations/DopplerLegacyClientImpl.ts
- src/implementations/HtmlEditorApiClientImpl.test.ts
- src/implementations/HtmlEditorApiClientImpl.ts
- src/implementations/dummies/doppler-legacy-client.tsx
Hi @FromDoppler/doppler-editors and @FromDoppler/doppler-webapp teams!
I think that my previous approach of avoiding exceptions completely when calling services is not sustainable.
It is easy that a developer forgot to add the full-scope try/catch.
So, I decided to keep the `Result` type for the happy path and for expected errors, for example, "not found", etc.
I think that this new approach also fits very well with React Query.
> Refactor unexpected errors

- src/implementations/dummies/html-editor-api-client.tsx
Hi team!
I think that these changes in our dummy HttpEditorApiClient implementation will be really useful to have a more real experience.
Here you have two examples:
**With the code as it is right now in `main` (without React Query)**
**With React Query (see #82)**
> chore: better data for demo in Dummy HtmlEditorApiClient

- src/components/Campaign.tsx
I think that our routings are enough restrictive, so, the Campaign component will not be renderer if the campaign id is _null_, _undefined_ or _empty_.
> Remove unnecessary validation of campaign ID

- src/components/Campaign.test.tsx
- src/components/Campaign.tsx
- src/components/SingletonEditor.tsx
As [we have discussed](https://makingsense.slack.com/archives/CLBEN4JAV/p1643828158421049), at the moment we are fine with `getUnlayerData` only.
> refactor: replace getDesign and getHtml by getUnlayerData

- src/components/Main.tsx
- src/index.tsx
Hi team!
I think that having `SingletonEditorProvider` in `index.tsx` makes it clear and predictable.
> refactor: move SingletonEditorProvider usage to index.tsx

- src/abstractions/domain/content.ts
- src/abstractions/html-editor-api-client/index.ts
- src/components/Campaign.test.tsx
- src/components/Campaign.tsx
- src/components/SingletonEditor.test.tsx
- src/components/SingletonEditor.tsx
- src/implementations/HtmlEditorApiClientImpl.test.ts
- src/implementations/HtmlEditorApiClientImpl.ts
- src/implementations/dummies/html-editor-api-client.tsx
- src/queries/campaign-content-queries.tsx
Hi team!
It is a preparation step to allow using [Unlayer HTML classic mode](https://examples.unlayer.com/web/legacy-template).
My idea is to have a new domain model `campaign`, by the moment it only supports drag-n-drop Unlayer model, but the next step is to support also support classic model:
```diff
export type Content =
+  | { htmlContent: string; type: "html" }
| { htmlContent: string; design: Design; type: "unlayer" };
```
> DE-450 - Preparation refactoring

- src/abstractions/domain/content.ts
- src/components/Main.tsx
- src/components/SingletonEditor.tsx
- src/implementations/HtmlEditorApiClientImpl.test.ts
- src/implementations/HtmlEditorApiClientImpl.ts
- src/implementations/dummies/html-editor-api-client.tsx
Hi team! 
These changes add support to HTML templates in our WebApp taking advantage of [Unlayer Legacy Template](https://examples.unlayer.com/web/legacy-template).
Example with the dummy API Client:
Note: this PR includes commits from #100. So, this PR will be easier to review after merge #100.
> DE-450 - Classic mode

- src/components/Editor.tsx
Hi team!
Doppler allows the user to edit the preheader text before editing the content. So, this should not be visible inside the email content editor.
> Remove Preheader Text from the editor

- .vscode/settings.json
I have used [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock)
to change the color of Visual Studio Code workspace to easily identify it
> Change VS Code IDE color

- package.json
- src/components/Editor.tsx
- yarn.lock
La configuración por defecto de los **_designTags** de Unlayer_ tenían conflicto con los **_idFields_** usados por Doppler, por eso se cambio el delimitador de los _**designTags**_ para que Unlayer al cargar el contenido no modifique los _**IdFields**_ de Doppler.
> [DE-526] Corregir error en la carga del contenido

- src/abstractions/app-session/app-session-state-accessor.ts
- src/abstractions/app-session/app-session-state-monitor.ts
- src/components/App.test.tsx
- src/components/AppSessionStateContext.tsx
- src/components/Campaign.test.tsx
- src/components/Editor.test.tsx
- src/components/Main.test.tsx
- src/components/SessionDemo.tsx
- src/components/SingletonEditor.test.tsx
- src/composition-root.ts
- src/implementations/DopplerRestApiClientImpl.test.ts
- src/implementations/DopplerRestApiClientImpl.ts
- src/implementations/HtmlEditorApiClientImpl.test.ts
- src/implementations/HtmlEditorApiClientImpl.ts
- src/implementations/app-session/polling-app-session-state-monitor.ts
- src/index.tsx
- src/queries/user-fields-queries.tsx
Working on an independent micro-frontend to deal with Doppler session management (see https://github.com/FromDoppler/doppler-session-mfe/pull/7), I found that we were messing it using the same object to represent the session wrapper (only useful on current session management implementation) and the session state accessor.
Also, there were some minor issues that, at the moment do not affect us, but they will if we improve the session management, for example using a cache.
The PR is XL, but I made it commit by commit, so, I think that it should be easy to follow.
Pending:
> Refactor and fix session management

- src/abstractions/app-session/app-session-state.ts
- src/components/AppServicesContext.test.tsx
- src/components/AppSessionStateContext.test.tsx
- src/components/AppSessionStateContext.tsx
- src/components/Editor.test.tsx
- src/components/RequireAuth.test.tsx
- src/implementations/app-session/doppler-mfe-app-session-state-monitor.ts
Ahora en el `AppSessionStateContext` tenemos el valor de _lang_ obtenido en la información de la sesión
> [DE-539] obtener sesión desde la información de usuario

- .vscode/launch.json
- src/components/Campaign.test.tsx
- src/components/EditorTopBar.test.tsx
- src/components/SingletonEditor.test.tsx
Hi team!
It is to allow us to easily debug the tests with VS Code.
If you want to run only one test, you can edit the file `.vscode/launch.json` updating `--testNamePattern`.
I had to also change the usage of `userEvent.click(el)` by `act(() => el.click())` because it was not working fine with the debugger (I googled it but I did not find anything).
> Debug with VS Code

- package.json
The flag `--openssl-legacy-provider` isn't working in all local environments.
> chore: update yarn test command

- src/components/Campaign.tsx
- src/components/SingletonEditor.test.tsx
- src/components/SingletonEditor.tsx
El objetivo es cambiar el comportamiento de `useSingletonEditor` para que permita configurar el editor y abstraer la lógica de _unMount_ que antes se encontraba en _/campaign_
> [DE-580] Refactorizar hook useSingletonEditor

- src/components/Campaign.test.tsx
- src/components/SingletonEditor.tsx
Se habilitan las pruebas de campaña que estaban comentadas por el error generado en el uso de portal para el _Header_ y _Footer_
[DE-583](https://makingsense.atlassian.net/browse/DE-583)
> [DE-583] habilitar pruebas comentadas por error con el uso de portal

- src/components/Campaign.test.tsx
- src/components/Campaign.tsx
Now, the exit button always goes to the campaigns' draft page.
> fix: exit button should point to campaign drafts

- src/components/Main.css
Related JIRA: [DE-678](https://makingsense.atlassian.net/browse/DE-678)
- Nav element extra padding removed
- Set grid template first row to auto, to prevent overlapping when hello bar is present
Before
After
> Css small change that affects menu-mfe layout

- src/components/Editor.tsx
**_Antes_** al cargar el editor de Unlayer se mostraba un texto.
https://user-images.githubusercontent.com/6733401/183470849-cd7a4b72-e29e-493f-b3c6-e111509cf3e5.mp4
**_Ahora_** se muestra un spinner mientras se esta realizando esta carga.
https://user-images.githubusercontent.com/6733401/183470706-7bded2bd-a094-49cc-a60d-e537d62275f8.mp4
> WIP [DE-721] Mostrar spinner cuando se cargan los user field's

- src/abstractions/domain/content.ts
- src/components/Campaign.tsx
- src/components/SingletonEditor.test.tsx
- src/components/i18n/en.tsx
- src/components/i18n/es.tsx
- src/implementations/HtmlEditorApiClientImpl.test.ts
- src/implementations/HtmlEditorApiClientImpl.ts
- src/implementations/dummies/html-editor-api-client.tsx
Ahora se muestra el nombre de la campaña en las campañas de tipo Unlayer
Related to:
* [PR-166](https://github.com/FromDoppler/doppler-html-editor-api/pull/166)
* [DE-688](https://makingsense.atlassian.net/browse/DE-688)
> [DE-688] Mostrar nombre de campaña en el editor de Unlayer

- src/components/Template.tsx
The footer buttons in template editor have the same design and behavior that in campaign editor, the only difference is that both button redirect to **/Template/Main**
https://user-images.githubusercontent.com/6733401/204587905-6744d7e9-5b23-4dd7-a670-0de27610dfb1.mp4
> [DE-896] Added button back and next in the template editor

- src/abstractions/html-editor-api-client/index.ts
- src/abstractions/services.ts
- src/components/App.tsx
- src/components/LoadingScreen.tsx
- src/components/SetCampaignContentFromTemplate.test.tsx
- src/components/SetCampaignContentFromTemplate.tsx
- src/implementations/HtmlEditorApiClientImpl.test.ts
- src/implementations/HtmlEditorApiClientImpl.ts
- src/implementations/dummies/html-editor-api-client.tsx
- src/queries/campaign-content-queries.tsx
Hi team!
Basically, these changes allow setting the campaign content from a template using a landing and then redirecting to edit the campaign.
https://user-images.githubusercontent.com/1157864/207949849-b1dc6059-0bdf-4577-b1a5-7cbfcfa834d0.mp4
> DE-910 - Content from template landing

- src/abstractions/configuration.ts
- src/components/EditorTopBar.test.tsx
- src/components/Template.test.tsx
- src/default-configuration.ts
I will use Templates URL to redirect back from Unlayer Editor in some circumstances.
Related to https://github.com/MakingSense/doppler-swarm/pull/716
> chore: add configuration for more Doppler's URLs

- src/components/Editor.tsx
Adding the URL base for Unlayer resources [DE-902](https://makingsense.atlassian.net/browse/DE-902)
[DE-902]: https://makingsense.atlassian.net/browse/DE-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DE-902] Base url asset for unlayer editor

- src/components/CreateTemplateFromTemplate.tsx
I am not sure if it is a good change, and I did not update the tests yet.
In my opinion, it is good because I am centralizing all redirect actions in only a declarative way, wrapping the usage of `window` global object.
> refactor: use declarative mode to redirect on error creating template from template

- src/abstractions/configuration.ts
- src/components/Campaign.tsx
- src/components/CreateTemplateFromTemplate.test.tsx
- src/components/CreateTemplateFromTemplate.tsx
- src/components/SetCampaignContentFromTemplate.test.tsx
- src/components/Template.tsx
- src/components/continuation-urls.test.tsx
- src/components/continuation-urls.ts
- src/default-configuration.ts
Hi team!
This change allows us to accept `next` and `exit` query-string parameters, enabling Doppler to decide what to do after editing content.
> DE-932 - Accept continuation URL parameters

- src/components/Campaign.test.tsx
- src/components/Campaign.tsx
- src/components/SaveAsTemplateModal.test.tsx
- src/components/Template.test.tsx
Added test for open modal behavior and success message.
Related to: [DE-896](https://makingsense.atlassian.net/browse/DE-869)
[DE-896]: https://makingsense.atlassian.net/browse/DE-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DE-869] Add test for export content as template

- src/implementations/HtmlEditorApiClientImpl.ts
When export content to template the requests threw an exception because the body was empty, now is sending the correct content data to create template.
https://user-images.githubusercontent.com/6733401/218569498-9ab502c0-14ed-4724-aba9-e57f0d07ce55.mp4
> Fix: Request to create template from content

- src/components/Campaign.test.tsx
Hi team!
I need to do some changes to campaign and template pages behavior related to smart save when the user exit.
I will need to update the tests, and after this refactoring, it will be easier for me and, if I am not wrong, for following code readers and editors.
> Refactor Campaign Page tests

- src/components/Campaign.test.tsx
- src/components/Campaign.tsx
- src/components/SingletonEditor.test.tsx
- src/components/SingletonEditor.tsx
- src/components/Template.tsx
Hi team!
These changes prevent the app from redundantly saving when the user exit and there are no pending changes.
> DE-960 - Smart save on exit

- src/components/SingletonEditor.tsx
When the auto-save is in progress and there are no new changes and the user exit from the editor, no new save should be done.
https://user-images.githubusercontent.com/1157864/222213703-e94fcc75-d8c4-47bc-8274-378691cf0952.mp4
https://user-images.githubusercontent.com/1157864/222213731-d27227ab-7dbb-462d-9488-c173a215fba9.mp4
> DE-960 - Avoid redundant saving on exit when ato-save is in progress

- cspell-project-words.txt
- src/abstractions/asset-manifest-client/index.ts
- src/abstractions/configuration.ts
- src/abstractions/services.ts
- src/components/Campaign.test.tsx
- src/components/Editor.test.tsx
- src/components/Editor.tsx
- src/components/SingletonEditor.test.tsx
- src/components/Template.test.tsx
- src/composition-root.ts
- src/default-configuration.ts
- src/implementations/MfeLoaderAssetManifestClientImpl.test.ts
- src/implementations/MfeLoaderAssetManifestClientImpl.ts
- src/implementations/SingletonLazyAppServicesContainer.ts
- src/queries/unlayer-editor-extensions-entrypoints.tsx
With these changes, we will get an advance of the new MFE Loader feature (see https://github.com/FromDoppler/mfe-loader/pull/104 and https://github.com/MakingSense/doppler-swarm/pull/730) and resolve the Unlayer Editor Extensions manifest here in place of delegate it to the Unlayer IFrame.
It should improve the performance and is also a step to fix the thumbnail generation.
> DE-904 - Resolve unlayer editor manifest

- src/abstractions/asset-manifest-client/index.ts
- src/components/Editor.test.tsx
- src/components/Editor.tsx
- src/implementations/MfeLoaderAssetManifestClientImpl.test.ts
- src/implementations/MfeLoaderAssetManifestClientImpl.ts
- src/queries/unlayer-editor-extensions-entrypoints.tsx
Hi team!
It prepares Editors WebApp to accept CSS from the Unlayer Extensions manifest.
> DE-968 - inject css unlayer extensions

- public/index.html
- src/components/SingletonEditor.tsx
Removed the unnecessary extension of the Unlayer editor types, the `UnlayerEditor` interface keeps giving extension to **_Unlayer's types_** when _EditorRef_ is inconsistent with the _Unlayer Object_
Relates to: [PR-481 ](https://github.com/FromDoppler/doppler-editors-webapp/pull/481 )
> Update the UnlayerEditor interface

- package.json
- src/components/SingletonEditor.tsx
- yarn.lock
I am replacing Underscore with Lodash because Jest fake timers were not working.
I wanted to use [this solution](https://stackoverflow.com/questions/52695553/testing-debounced-function-in-react-component-with-jest-and-enzyme#answer-64336022) in a test, but it does not work with Underscore, I suppose that it is related to [this issue](https://github.com/jashkenas/underscore/issues/2918).
> Replace underscore by lodash

- src/components/Campaign.test.tsx
- src/components/Campaign.tsx
- src/components/Main.tsx
- src/components/Template.test.tsx
- src/components/Template.tsx
- src/components/singleton-editor/SingletonEditorProvider.test.tsx
- src/components/singleton-editor/SingletonEditorProvider.tsx
- src/components/singleton-editor/index.ts
- src/components/singleton-editor/singletonDesignContext.ts
- src/components/singleton-editor/useSingletonEditor.ts
- src/utils/index.ts
Hi team!
As I already mentioned in #526, I am in the way of refactoring SingletonEditor's state:
* Use reducer-based state in place of refs
* Split files and behavior
* Add tests
This is the first step. I am only moving files, renaming things, etc. Nothing in the behavior should be changed.
After this, I will create a new PR with the real refactoring (and a slight change in the behavior) 
Oh, I have also done two minor fixes related to export as template functionality.
> Editor state's refactoring - step 1/2

- src/components/singleton-editor/reducer.test.ts
- src/components/singleton-editor/reducer.ts
- src/components/singleton-editor/useSaving.test.tsx
- src/components/singleton-editor/useSaving.ts
- src/components/singleton-editor/useSingletonEditorState.test.tsx
- src/components/singleton-editor/useSingletonEditorState.ts
- src/utils/index.ts
Now, we are catching the errors in the saving process.
For the moment, it is only shown as _"Saving..."_, and it is fixed when there is a successful saving.
in the future, we could show the error in a different way.
> Gracefuly deal with saving errors

- src/abstractions/domain/editor.ts
- src/components/Campaign.test.tsx
- src/components/Template.test.tsx
- src/components/custom-media-library/CustomMediaLibrary.tsx
- src/components/custom-media-library/CustomMediaLibraryModal.tsx
- src/components/custom-media-library/index.ts
- src/components/custom-media-library/useCustomMediaLibraryModal.test.tsx
- src/components/singleton-editor/SingletonEditorProvider.test.tsx
- src/components/singleton-editor/useCustomMediaLibrarySetup.test.tsx
- src/components/singleton-editor/useCustomMediaLibrarySetup.ts
- src/components/singleton-editor/useSingletonEditor.ts
Hi team! 
It is the first step to using the MSEditor Gallery instead of the out-of-the-box Unlayer Gallery.
The gallery component is not ready yet, so the component is not initialized in the Singleton Editor.
Related documentation: https://examples.unlayer.com/media/custom-media-library/
https://github.com/FromDoppler/doppler-editors-webapp/assets/1157864/3ce3ab05-6c14-40d4-8548-0ccc9ed9fd62
> DOP-1346 - MSEditor Gallery (Step 1/?)

- src/queries/image-gallery-queries.tsx
After uploading items, we are cleaning the search terms to ensure to show the newly uploaded item.
It was generating two requests in place of one:
https://github.com/FromDoppler/doppler-editors-webapp/assets/1157864/e34aaaf4-c174-4fb5-b0b0-9470cca9122e
Now, it is fixed:
https://github.com/FromDoppler/doppler-editors-webapp/assets/1157864/53070716-2ae4-4d5f-ab49-6b799bef6a7c
> Avoid double request after upload file

- src/components/singleton-editor/useSaving.test.tsx
- src/components/singleton-editor/useSaving.ts
Cuando falla la generación del thumbnail usaremos una imagen temporal para permitir que el guardar siga funcionando
> Quick and dirty fix to allw saving when thumbnail generation does not work

- src/abstractions/common/result-types.ts
- src/abstractions/doppler-legacy-client/index.ts
- src/abstractions/editor-extensions-bridge/index.ts
- src/abstractions/editor-extensions-listeners/index.ts
- src/abstractions/services.ts
- src/components/Campaign.test.tsx
- src/components/singleton-editor/SingletonEditorProvider.test.tsx
- src/composition-root.ts
- src/implementations/DopplerLegacyClientImpl.test.ts
- src/implementations/DopplerLegacyClientImpl.ts
- src/implementations/SingletonLazyAppServicesContainer.ts
- src/implementations/dummies/doppler-legacy-client.tsx
- src/implementations/editor-extensions-bridge/index.test.ts
- src/implementations/editor-extensions-bridge/index.ts
- src/implementations/editor-extensions-listeners/index.test.ts
- src/implementations/editor-extensions-listeners/index.ts
- src/index.tsx
In this PR we are adding a listener for the `getPromoCodes` message, asking the backend for the data, and returning the result to the editor's extensions following the convention defined in https://github.com/FromDoppler/unlayer-editor/pull/927
> DOP-1418 - Promo codes

- src/components/UnlayerEditorWrapper.tsx
Hide send test email button on preview modal
> DOP-1483 - Hide send test button

- src/implementations/DopplerLegacyClientImpl.ts
receive continuation from Doppler, and pass it the same when the user is scrolling.
> feat: handle 'continuation' without concerning its internal meaning

- src/components/base-gallery/SidePanel.tsx
- src/components/product-gallery/HeaderSortProductsDropdown.tsx
Hide Dropdown when a store or e-commerce has not sort support 
case no sort criteria without products
case with sort support with products
case with sort support without products
> DOP-1399 - Product gallery hide dropdown

- src/components/UnlayerEditorWrapper.tsx
fix: set to 1.5.75 unlayer version
[docs](https://docs.unlayer.com/page/introducing-new-unlayer-editor#breaking-changes)
> DOP-1547- lock unlayer version

- src/abstractions/doppler-legacy-client/index.ts
- src/components/Campaign.test.tsx
- src/components/Template.test.tsx
- src/components/singleton-editor/SingletonEditorProvider.test.tsx
- src/components/singleton-editor/useGenerateThumbnail.ts
- src/components/singleton-editor/useSaving.test.tsx
- src/components/singleton-editor/useSaving.ts
- src/components/singleton-editor/useSingletonEditor.ts
- src/implementations/DopplerLegacyClientImpl.ts
- src/implementations/dummies/doppler-legacy-client.tsx
- src/queries/campaign-content-queries.tsx
fix: replace request generate unlayer preview image by doppler generate thumb
Trouble: Each content update unlayer saves the change, in this procedure, call a method to generate a content image preview after that save the content with an image associate. That generates a new image impacting the s3 storage with unused image files.
> DOP-1575 - Replace unlayer preview

- src/abstractions/doppler-legacy-client/index.ts
- src/components/custom-media-library/CustomMediaLibraryModal.tsx
- src/implementations/DopplerLegacyClientImpl.ts
- src/implementations/dummies/doppler-legacy-client.tsx
- src/queries/campaign-content-queries.tsx
Fix: set a gallery image as an image campaign
> DOP-1577 - Set image as campaign content from gallery

- src/abstractions/doppler-legacy-client/index.ts
- src/components/singleton-editor/useImageUploadSetup.test.tsx
- src/components/singleton-editor/useImageUploadSetup.ts
- src/components/singleton-editor/useSingletonEditor.ts
- src/implementations/DopplerLegacyClientImpl.test.ts
- src/implementations/DopplerLegacyClientImpl.ts
- src/implementations/dummies/doppler-legacy-client.tsx
- src/queries/campaign-content-queries.tsx
Fix: Add unlayer image callback
when the user adds an image from unlayer gallery, edits the image, or creates with IA this file is stored at Doppler system file.
unlayer image callback [doc ](https://docs.unlayer.com/docs/custom-file-storage)
Note: the backend for images over 3 Mb does a compression process to reduce the size
When the endpoint throws an error, the callback returns https://cdn.tools.unlayer.com/image/placeholder.png as the image
error case: 
TODO: watch unalyer release if add a error callback
> DOP-1581 - Image campaign upload

- src/components/singleton-editor/useImageUploadSetup.ts
Fix: add template prefix when an image is saved from a template
[DOP-1691](https://makingsense.atlassian.net/browse/DOP-1691)
issue
resolve
[DOP-1691]: https://makingsense.atlassian.net/browse/DOP-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOP-1691 - Add prefix for template

- src/components/Campaign.tsx
- src/components/Template.tsx
Fix: resolve document name for empty name
[DOP-1738](https://makingsense.atlassian.net/browse/DOP-1738)
[DOP-1738]: https://makingsense.atlassian.net/browse/DOP-1738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOP-1738 - Resolve document name for empty name (fix)

- src/abstractions/domain/product-gallery.ts
- src/implementations/DopplerLegacyClientImpl.ts
- src/implementations/dummies/doppler-legacy-client.tsx
With this fix, when we replace dynamic HTML content with product information, we can now display the ```InfoHtml```
> fix: use infohtml instead info
