FromDoppler/doppler-editors-webapp

README.md, demo/demo.html
It is a mini-introduction about what this project is and how to use it. Could you kindly review it?
=> Some documentation

Jenkinsfile, build-n-publish.sh, cdn-helpers/upload.sh, demo/demo.html
Based on this conversation: https://makingsense.slack.com/archives/CLBEN4JAV/p1639496774394000?thread_ts=1639496483.393500&cid=CLBEN4JAV
=> Renaming editors-ufe as editors-webapp

package.json
=> chore: fix package name

demo/index.html, demo/start-demo.sh
=> Add an easy way to start demo page

src/App.test.tsx, src/App.tsx, src/Main.test.tsx, src/Main.tsx, src/index.tsx, src/reportWebVitals.ts, src/routes/expenses.tsx, src/routes/invoices.tsx
=> Avoid default exports

src/components/Editor.tsx
Minor changes related to deal with defective Unlayer types.
=> Unlayer types improvements

src/index.tsx
@Cromeror you thought that I would never do it, did not you? 😛
=> chore: remove reading of a deprecated configuration entry

src/components/RequireAuth.test.tsx, src/components/RequireAuth.tsx
It will allow going back to the desired URL after successful login.
Related to https://github.com/FromDoppler/doppler-webapp/pull/1816
=> Redirect back after login

src/__mocks__/react-email-editor.tsx, src/components/Editor.test.tsx, src/components/Editor.tsx
Based on https://docs.unlayer.com/docs/react-component#usage
=> fix: use onLoad handler in place of useEffect for loading editor design

src/abstractions/app-session/app-session-state.ts, src/abstractions/doppler-legacy-client/index.ts, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/app-session/pulling-app-session-state-monitor.ts, src/implementations/dummies/doppler-legacy-client.tsx
Hi team!
I will need `dopplerAccountName` in my next step, and probably we will need  `fullname`, `lang` and `avatar` in the near time.
=> Session data

src/components/Campaign.tsx, src/components/Editor.tsx, src/components/Template.tsx
Today I have talked with @Cromeror and he enlightened me about how to make this component efficient.
I tested it and it works great!
=> fix: support loading design in a existent EmailEditor

src/abstractions/html-editor-api-client/index.ts, src/abstractions/services.ts, src/components/Campaign.test.tsx, src/components/Campaign.tsx, src/composition-root.ts, src/implementations/SingletonLazyAppServicesContainer.ts, src/implementations/dummies/html-editor-api-client.tsx, src/implementations/dummies/sample-unlayer-design.json
It is working now!
One commit is overlapped with #53
=> DE-399 - Get dummy campaign content

src/components/Campaign.tsx, src/components/Editor.tsx, src/components/Template.tsx
Hi @Cromeror, I think that it fills a gap in Editor component implementation.
I know that you are re-implementing this component, but probably it is still useful in your new implementation.
=> Unload design from Editor when it is not defined

src/components/Editor.tsx
Very minor missing cleanup in Editor component.
=> fix: unload design on un-mounting editor component

src/components/Campaign.tsx, src/components/Main.tsx, src/components/SingletonEditor.test.tsx, src/components/SingletonEditor.tsx
Hi team!
This is arguable, what is more, both PRs are independently arguable.
=> Minor refactoring

package.json, src/components/Campaign.test.tsx, src/components/Campaign.tsx, src/index.tsx, src/queries/campaign-content-queries.tsx, yarn.lock
Hi team!
With these changes, we will use [React Query](https://react-query.tanstack.com/) to get the campaign content.
By the moment, we are not taking so many advantages of this (notice that I have disabled _refetchOnMount_, _refetchOnWindowFocus_, and _refetchOnReconnect_), but now the code is more declarative, we are supporting with unmounting during fetch, and I think that in the future it will give us much more.
Please, review it commit by commit, some refactoring steps could be arguable and we can omit some of them if you want.
=> React Query

src/abstractions/html-editor-api-client/index.ts, src/components/Campaign.test.tsx, src/components/Campaign.tsx, src/implementations/HtmlEditorApiClientImpl.ts, src/implementations/dummies/html-editor-api-client.tsx, src/queries/campaign-content-queries.tsx
Hi Team!
It is what we need to save the campaign content using our API.
=> Save model using API

src/components/Campaign.test.tsx, src/components/Main.tsx, src/components/SingletonEditor.test.tsx, src/components/SingletonEditor.tsx
I am moving SingletonEditor related code from Main to the right module.
=> Encapsulate SingletonEditor code

src/components/AppSessionStateContext.tsx, src/components/Editor.test.tsx, src/components/Editor.tsx, src/components/RequireAuth.test.tsx, src/components/RequireAuth.tsx, src/components/SessionDemo.tsx
Hi team!
It fixes an inconsistency in the rendering of the Editor component and also improves our code to make the session usage simpler in the React Components.
Thanks @Cromeror for your help!!
=> Fix editor re-rendering

src/abstractions/configuration.ts, src/composition-root.ts, src/default-configuration.ts, src/implementations/DopplerRestApiClientImpl.test.ts, src/implementations/DopplerRestApiClientImpl.ts
Hi Team!
It implements the query to our Doppler REST API to get the custom fields, could you review it?
=> DE-451 - Query real backend for fields

package.json, src/components/App.test.tsx, src/components/Campaign.test.tsx, src/components/Campaign.tsx, src/components/Editor.tsx, src/components/EditorBottomBar.css, src/components/EditorBottomBar.tsx, src/components/EditorTopBar.css, src/components/EditorTopBar.tsx, src/components/Main.css, src/components/Main.test.tsx, src/components/Main.tsx, src/components/SingletonEditor.tsx, src/index.css, src/index.tsx
=> De-486 layout editor

src/components/Editor.tsx
Based on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58921
I have tested it in INT environment.
=> Use EmailEditor.onReady in place of onLoad

src/components/EditorTopBar.css, src/components/EditorTopBar.tsx
=> feat: add markup for app header

package.json, src/abstractions/configuration.ts, src/components/DropdownButton.tsx, src/components/EditorTopBar.test.tsx, src/components/EditorTopBar.tsx, src/default-configuration.ts, yarn.lock
Ticket [DE-525](https://makingsense.atlassian.net/browse/DE-525)
https://user-images.githubusercontent.com/45947909/159354010-c5bed985-964b-44f5-aff3-d70f02fb884b.mp4
=> [DE-525] Update exit menu behaviour

src/components/Editor.tsx
Ticket [DE-506](https://makingsense.atlassian.net/browse/DE-506)
---
=> [DE-506] Set tools dock to left

src/abstractions/configuration.ts, src/default-configuration.ts, src/index.tsx
Related To: [DOM-297](https://makingsense.atlassian.net/browse/DOM-297)
=> [DOM-297] Changes in tag id elements

package.json, src/components/Campaign.test.tsx, src/components/Campaign.tsx, src/components/EditorBottomBar.tsx, src/components/EditorTopBar.test.tsx, src/components/EditorTopBar.tsx, src/components/i18n/DopplerIntlProvider.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx, src/components/i18n/utils.tsx, src/index.tsx, yarn.lock
Por el momento, hardcodeando el atributo locale, permite traducir los elementos de la webapp del editor.
**Inglés**
**Español**
=> [DE-508] Add multi language support

src/components/Campaign.test.tsx, src/components/EditorTopBar.test.tsx, src/components/i18n/TestDopplerIntlProvider.tsx
Hi team!
These changes allow us to ignore the translation literals in the tests and simply use the keys.
=> DE-541 - Test language provider

src/components/i18n/DopplerIntlProvider.test.tsx, src/components/i18n/DopplerIntlProvider.tsx, src/components/i18n/TranslationFiles.test.tsx, src/components/i18n/utils.tsx
Team, we're adding tests to translation files and DopplerIntlProvider
=> [DE-508] Update tests

src/components/App.test.tsx, src/components/Editor.test.tsx, src/components/Editor.tsx, src/components/Main.test.tsx, src/components/SingletonEditor.test.tsx
=> [DE-509] Add locale to Unlayer based on user session language

src/components/DropdownButton.tsx
=> fix: add arrow dropdown

src/components/Editor.tsx
Related to https://github.com/FromDoppler/unlayer-editor/pull/311, https://github.com/FromDoppler/unlayer-editor/pull/312 and https://github.com/FromDoppler/unlayer-editor/pull/313
=> DE-570 - initialize Unlayer Editor extensions

src/components/Campaign.tsx, src/components/EditorBottomBar.test.tsx, src/components/EditorBottomBar.tsx
https://user-images.githubusercontent.com/45947909/164320475-4102c38a-669e-4db0-9524-160b4d00df8c.mp4
=> [DE-566] Add click behaviour to bottom bar next button

src/components/Campaign.tsx, src/components/EditorBottomBar.test.tsx, src/components/EditorBottomBar.tsx
=> [DE-565] Exit button bottom bar

src/components/Campaign.tsx
Links with parameters `?redirectedFromSummary=true&idABTest=14120`
---
Links with parameters `?redirectedFromSummary=false&idABTest=14120`
=> [DE-505] Update links based on idABTest parameter

package.json, src/components/SingletonEditor.test.tsx, src/components/SingletonEditor.tsx, yarn.lock
=> Minor fixes

src/abstractions/domain/content.ts, src/components/SingletonEditor.test.tsx, src/components/SingletonEditor.tsx, src/implementations/HtmlEditorApiClientImpl.test.ts, src/implementations/HtmlEditorApiClientImpl.ts, src/implementations/dummies/html-editor-api-client.tsx, src/utils/index.ts
Hi team!
It is generating the preview image and sends it to the backend along with the HTML and design.
=> DE-561 - generate thumbnail

src/components/SingletonEditor.tsx
Se está gestionando el guardado sincronizando las invocaciones al método guardar que hace el usuario con las que se hacen automáticamente.
Casos contemplados:
- Si hubo cambios y el usuario oprime guardar el auto guardado se invalida.
- Si después que el usuario oprime guardar se realizan cambios, estos se guardan automáticamente.
[[DE-629]](https://makingsense.atlassian.net/browse/DE-629)
[DE-629]: https://makingsense.atlassian.net/browse/DE-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DE-629] arreglada sincronización entre el auto guardado y el guardado manual del usuario

src/components/Campaign.test.tsx, src/utils/testPortalUtils.tsx
estas pruebas aseguran que los botones de continuar se construyan con las URL deseadas según el parámetro `RedirectedFromTemplateList` que reciba el editor.
=> [DE-583] agregando test para el footer en campaña

package.json, yarn.lock
=> Dependencies 2022-06-14 A

src/implementations/dummies/sample-unlayer-design.json
Very minor change related to https://github.com/FromDoppler/doppler-html-editor-api/pull/120
=> chore: set 600px with in the dummy unlayer content

src/components/Campaign.test.tsx, src/components/Campaign.tsx, src/components/EditorBottomBar.css, src/components/LoadingScreen.tsx, src/components/Main.css, src/components/RequireAuth.test.tsx, src/components/RequireAuth.tsx
https://user-images.githubusercontent.com/6733401/181352166-ade8921e-4638-45fb-ab87-f5dc6b2a8005.mp4
Related to: [DE-698](https://makingsense.atlassian.net/browse/DE-698)
=> [DE-698] Spinners en editor Unlayer en lugar de textos

src/implementations/app-session/doppler-mfe-app-session-state-monitor.ts
See details: https://github.com/FromDoppler/doppler-session-mfe/pull/101
=> chore: update Session MFE types

src/abstractions/domain/content.ts, src/abstractions/html-editor-api-client/index.ts, src/components/Campaign.tsx, src/components/SingletonEditor.test.tsx, src/components/SingletonEditor.tsx, src/components/Template.test.tsx, src/components/Template.tsx, src/implementations/HtmlEditorApiClientImpl.test.ts, src/implementations/HtmlEditorApiClientImpl.ts, src/implementations/dummies/html-editor-api-client.tsx, src/queries/campaign-content-queries.tsx, src/queries/template-queries.tsx
=> DE-870 - Load and show template (not saving yet)

src/abstractions/html-editor-api-client/index.ts, src/components/Campaign.test.tsx, src/components/Template.test.tsx, src/components/Template.tsx, src/implementations/HtmlEditorApiClientImpl.test.ts, src/implementations/HtmlEditorApiClientImpl.ts, src/implementations/dummies/html-editor-api-client.tsx, src/queries/template-queries.tsx
It allows the user to save the changes in his templates.
=> DE-870 - Save template

src/abstractions/configuration.ts, src/components/Editor.tsx, src/default-configuration.ts
Related to: https://makingsense.atlassian.net/browse/DE-895
=> [DE-895] Update button tool icon

package.json, src/components/App.test.tsx, src/components/Campaign.test.tsx, src/components/Editor.test.tsx, src/components/Main.test.tsx, src/components/SingletonEditor.test.tsx, src/components/Template.test.tsx, src/index.tsx, src/queries/campaign-content-queries.tsx, src/queries/template-queries.tsx, src/queries/user-fields-queries.tsx, yarn.lock
Thanks @mcappato for the heads up!
=> fix(deps): upgrade to React-Query v4 final

src/components/Main.tsx
Fix: https://makingsense.atlassian.net/browse/DE-905
=> [DE-905] Adjust editor height

src/abstractions/html-editor-api-client/index.ts, src/components/App.tsx, src/components/CreateTemplateFromTemplate.test.tsx, src/components/CreateTemplateFromTemplate.tsx, src/components/SetCampaignContentFromTemplate.test.tsx, src/implementations/HtmlEditorApiClientImpl.test.ts, src/implementations/HtmlEditorApiClientImpl.ts, src/implementations/dummies/html-editor-api-client.tsx, src/queries/template-queries.tsx
I am applying the same pattern than in #374
=> DE-911 - Landing for creating a template based on another template

src/components/Campaign.tsx, src/components/SingletonEditor.tsx
Before was exported the content of campaign editor and now is export the design that is current edited on the unlayer editor.
=> [DE-869] Exporting current content design

src/components/Campaign.test.tsx, src/components/Campaign.tsx, src/components/EditorBottomBar.test.tsx, src/components/EditorBottomBar.tsx, src/components/Template.test.tsx, src/components/Template.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx, src/components/smart-urls.tsx
**BEFORE** did show message when the user try leave the editor without save.
https://user-images.githubusercontent.com/6733401/219058400-ef6b0226-1246-48a3-8a1e-a65b25b5c366.mp4
<br/>
**NOW** don't shows exit message because the content is saved when click in exit or continue button
https://user-images.githubusercontent.com/6733401/219058953-8dbaec96-fe56-4d8f-ad9f-755d4311b10b.mp4
=> [DE-947] Save content when exit the editor

src/components/Campaign.tsx, src/components/EditorBottomBar.css, src/components/SavingMessage.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx
Showing message when saving content in the corner bottom-rigth
https://user-images.githubusercontent.com/6733401/220932513-29d94caa-609e-4b23-a463-f403944e690d.mp4
**_nota:_** The CSS animation will be in the StyleGuide.
=> [DE-808] Show message when the content is saving

src/components/EditorBottomBar.css
Move to the right/button corner
Related to: https://makingsense.atlassian.net/browse/DE-808
=> [DE-808] Saving label position

src/components/Template.test.tsx
Hi team!
This is the twin PR of #438 but for Templates.
Could you review?
=> Refactor Template Page tests

src/components/Template.tsx
Related to  [DE-966](https://makingsense.atlassian.net/browse/DE-966)
[DE-966]: https://makingsense.atlassian.net/browse/DE-966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DE-966] Show message when template is saving

src/components/Campaign.tsx, src/components/SingletonEditor.test.tsx, src/components/SingletonEditor.tsx, src/components/Template.tsx
Problema:
Corregido y probado en INT:
=> Wait to save before navigating

src/components/Editor.tsx
=> Move body tab up

src/components/Campaign.tsx
Related: https://github.com/FromDoppler/doppler-style-guide/pull/290
=> fix: add margin left

src/components/Campaign.tsx
=> Change button as secondary

cspell-project-words.txt, src/components/UnlayerEditorWrapper.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx, src/components/useCustomFields.test.tsx, src/components/useCustomFields.ts, src/utils/index.test.ts, src/utils/index.ts
=> DE-992 - translate and sort field names

src/abstractions/domain/image-gallery.ts, src/abstractions/doppler-legacy-client/index.ts, src/abstractions/services.ts, src/components/custom-media-library/CustomMediaLibrary.tsx, src/components/custom-media-library/CustomMediaLibraryModal.test.tsx, src/components/custom-media-library/List.tsx, src/components/custom-media-library/types.ts, src/components/custom-media-library/useCustomMediaLibraryBehavior.test.tsx, src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx, src/composition-root.ts, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/SingletonLazyAppServicesContainer.ts, src/implementations/dummies/doppler-legacy-client.tsx, src/queries/image-galleries-queries.tsx
In this PR I am connecting the WIP Gallery with the Doppler backend.
Currently, I am taking only the newest 50 images without the possibility of pagination, sorting, or searching.
=> DOP-1346 - MSEditor Gallery (Step 3/?)

src/components/App.test.tsx, src/components/CreateTemplateFromTemplate.test.tsx, src/components/Main.test.tsx, src/components/SetCampaignContentFromTemplate.test.tsx, src/components/UnlayerEditorWrapper.test.tsx, src/components/custom-media-library/CustomMediaLibraryModal.test.tsx, src/components/custom-media-library/useCustomMediaLibraryBehavior.test.tsx, src/components/singleton-editor/SingletonEditorProvider.test.tsx
Hi team!
I am cleaning up some tests, and isolating React Query's QueryClient. It was generating unexpected behaviors in the tests because the same client was shared between different tests.
=> Improve tests

src/components/custom-media-library/CustomMediaLibrary.tsx
Required by https://github.com/FromDoppler/doppler-style-guide/pull/310
=> DOP-1366 - Fix custom media gallery layout

src/components/custom-media-library/CustomMediaLibrary.test.tsx, src/components/custom-media-library/CustomMediaLibrary.tsx, src/components/custom-media-library/List.tsx
https://github.com/FromDoppler/doppler-editors-webapp/assets/1157864/0a1e1a96-9091-45c2-9dec-a6f94bc46b18
=> Select image with double click

package.json
From https://stackoverflow.com/questions/73958968/cannot-use-import-statement-outside-a-module-with-axios#answer-74297004
=> Fix axios/jest interaction error in Windows

src/components/custom-media-library/CustomMediaLibrary.test.tsx, src/components/custom-media-library/CustomMediaLibraryModal.test.tsx, src/components/custom-media-library/Footer.tsx, src/components/custom-media-library/List.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx
- change literal text by itl resourses
- add test if exist upload button
=> DOP-1369  - Update content custom media library

src/components/custom-media-library/CustomMediaLibrary.tsx, src/components/custom-media-library/CustomMediaLibraryModal.test.tsx, src/components/custom-media-library/List.tsx, src/components/custom-media-library/Loading.tsx, src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx
https://github.com/FromDoppler/doppler-editors-webapp/assets/1157864/e72ed7aa-43b3-456f-8c13-a15804bbf332
=> DOP-1346 - loading

src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts
=> Use URLSearchParams to create the query-string in media gallery

cspell-project-words.txt, src/components/custom-media-library/Content.tsx, src/components/custom-media-library/ContentEmpty.tsx, src/components/custom-media-library/ContentNoResult.tsx, src/components/custom-media-library/LibraryUI.test.tsx, src/components/custom-media-library/LibraryUI.tsx, src/components/custom-media-library/behavior.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx
=> DOP-1375 - Message when there are no results

src/abstractions/doppler-legacy-client/index.ts, src/components/custom-media-library/DeleteConfirmationModal.tsx, src/components/custom-media-library/HeaderDeleteButton.tsx, src/components/custom-media-library/LibraryUI.test.tsx, src/components/custom-media-library/LibraryUI.tsx, src/components/custom-media-library/behavior.test.tsx, src/components/custom-media-library/behavior.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx, src/queries/image-gallery-queries.tsx
https://github.com/FromDoppler/doppler-editors-webapp/assets/1157864/7da6fc27-9bad-418b-bd06-eb4b6438702e
**To do before merging:** Review styles and implementation with Gina and @GusBaamonde.
=> DOP-1367 - Delete selected images

cspell-project-words.txt, src/abstractions/i18n.ts, src/components/i18n/DopplerIntlProvider.test.tsx, src/components/i18n/DopplerIntlProvider.tsx, src/components/i18n/TestDopplerIntlProvider.tsx, src/components/i18n/TranslationFiles.test.tsx, src/components/i18n/en.tsx, src/components/i18n/setup.ts, src/components/i18n/utils.tsx
Hi team!
With these changes, we will get rapid feedback when we have a typo in a translation id.
=> Typesafe translations

src/components/confirmation/Confirmation.tsx, src/components/confirmation/ConfirmationModal.tsx, src/components/confirmation/useConfirmationModal.tsx, src/components/custom-media-library/behavior.test.tsx, src/components/custom-media-library/behavior.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx
I am removing some hardcoded customizations and improving the confirmation UI.
=> Gallery modals UI

demo/index.html, public/index.html, src/abstractions/configuration.ts, src/components/UnlayerEditorWrapper.tsx, src/default-configuration.ts
Related to https://github.com/FromDoppler/unlayer-editor/pull/907 and https://github.com/MakingSense/doppler-swarm/pull/787
=> Preview mode

src/components/Campaign.tsx, src/components/DropdownButton.tsx, src/components/SaveAsTemplateModal.tsx, src/components/Template.tsx, src/components/custom-media-library/FooterUploadButton.tsx
Related to https://github.com/FromDoppler/doppler-style-guide/pull/364 and https://github.com/FromDoppler/doppler-style-guide/pull/366
=> Tertiary button and exit menu

src/components/UnlayerEditorWrapper.test.tsx, src/components/UnlayerEditorWrapper.tsx
Related to https://github.com/FromDoppler/unlayer-editor/pull/975
=> Pass dopplerExternalUrls values to Unlayer extensions

src/components/base-gallery/ContentList.tsx, src/components/base-gallery/GalleryItem.ts, src/components/custom-media-library/ContentList.tsx, src/components/custom-media-library/CustomMediaLibraryModal.tsx, src/components/custom-media-library/LibraryUI.test.tsx, src/components/custom-media-library/LibraryUI.tsx, src/components/custom-media-library/behavior.test.tsx, src/components/custom-media-library/behavior.tsx, src/components/product-gallery/ProductGalleryUI.test.tsx, src/components/product-gallery/ProductGalleryUI.tsx, src/components/product-gallery/product-gallery-behavior.ts, src/queries/image-gallery-queries.tsx
It is a big, but simple, code refactoring of some names. It also adds a wrapper for the ContentList's items to add an abstraction between ContentList and ContentList's items type.
=> DOP-1398 - More generalistic gallery implementation

cspell-project-words.txt, src/abstractions/domain/DopplerEditorSettings.ts, src/abstractions/doppler-legacy-client/index.ts, src/components/UnlayerEditorWrapper.test.tsx, src/components/base-gallery/SidePanel.tsx, src/components/i18n/en.tsx, src/components/i18n/es.tsx, src/components/product-gallery/ProductGalleryUI.test.tsx, src/components/product-gallery/ProductGalleryUI.tsx, src/components/product-gallery/product-gallery-behavior.test.tsx, src/components/product-gallery/product-gallery-behavior.ts, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx, src/queries/products-gallery-queries.tsx
Add side panel with integration store on getsettings data
Next steps:
- Add dynamically sorts by integration support
- update product list view 
https://github.com/FromDoppler/doppler-editors-webapp/assets/83654756/3e0b4936-963b-4538-9432-f790de3f27b2
=> DOP-1471 Product gallery content store panel

src/abstractions/doppler-legacy-client/index.ts, src/components/base-gallery/SidePanel.tsx, src/components/product-gallery/ProductGalleryUI.test.tsx, src/components/product-gallery/ProductGalleryUI.tsx, src/components/product-gallery/product-gallery-behavior.test.tsx, src/components/product-gallery/product-gallery-behavior.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx, src/queries/products-gallery-queries.tsx
Refactor update store state type from string to store object
=> DOP-1399 - Product gallery content store refact

src/abstractions/domain/DopplerEditorSettings.ts, src/abstractions/doppler-legacy-client/index.ts, src/components/UnlayerEditorWrapper.tsx, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx, src/queries/editor-settings-queries.tsx
Replace GetStaticUserSettings by GetSettings
Add abandonedCartCampaign attribute to ["unlayer-extensions-configuration"]
=> DOP-1397  - Update get settings method

src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx
add flag visitedProductsCampaign
=> DOP-1399 - Add visited products campaign flag

src/abstractions/domain/DopplerEditorSettings.ts
fix: add visitedProductsCampaign as property for DopplerEditorSettings type
=> DOP-1399 - Add visitedProductsCampaign property

src/components/custom-media-library/CustomMediaLibraryModal.test.tsx, src/implementations/DopplerLegacyClientImpl.ts
Add rule to ensure only one parameter in the request
=> DOP-1399 - Fix get settings request

src/abstractions/domain/DopplerEditorSettings.ts, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx
Add settings flags:
- pendingOrderCampaign
- confirmationOrderCampaign
for order details component
=> DOP-1402 - enable order details unlayer

src/abstractions/domain/DopplerEditorSettings.ts, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx
Add recommended product types flags
=> DOP-1401 - recommended product tool

src/components/UnlayerEditorWrapper.tsx
fix: set last unlayer version 1.9.0
=> DOP-1547 - Set unlayer version

src/abstractions/domain/DopplerEditorSettings.ts, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx
=> DOP-1403 - Add rss flags

src/components/singleton-editor/useEditorExtensionListeners.test.tsx, src/components/singleton-editor/useEditorExtensionListeners.ts
Fix: add listener to save QR image at dopplerFiles
=> DOP-1593 - Save qr image

src/components/singleton-editor/useImageUploadSetup.test.tsx, src/components/singleton-editor/useImageUploadSetup.ts
Fix: 
- add idCampaign as prefixe for upload image
- update logic for normalice filename extension
=> DOP-1671 - fix image overwrite

src/components/UnlayerEditorWrapper.tsx
fix update unlayer version from 1.9.0 to 1.101.0 (last stable)
[Unlayer changelog](https://changelog.unlayer.com/en)
=> Update unlayer version

src/abstractions/domain/DopplerEditorSettings.ts, src/abstractions/domain/product-gallery.ts, src/components/product-gallery/product-gallery-behavior.test.tsx, src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx
Fix:
Add flag dynamic product enable by store
Add new properties (reference, info) for product gallery
=> DOP-1800 - Add product dynamic

src/implementations/DopplerLegacyClientImpl.test.ts, src/implementations/DopplerLegacyClientImpl.ts, src/implementations/dummies/doppler-legacy-client.tsx
Al haber presencia de productos dinámicos, filtramos todas aquellas tiendas que posean la propiedad dynamicProductEnabled en true.
=> Doi 2080 filtrar stores dynamic product
